### ISSUE TITLE
lemmatizer BOW/EOW confusion

### ISSUE THREAD

**Issue by Sejsel** [ufal/npfl114#148]
[This comment](https://github.com/ufal/npfl114/blob/master/labs/09/lemmatizer_attn.py#L211=) (and a few others, in the other files as well) mention `[EOW]`, but it is actually `[BOW]` in the results. This is because `BOW` and `EOW` are both defined as `1` in the [MorphoDataset](https://github.com/ufal/npfl114/blob/a339f9ecc5bc71a719e56a507db9e1c8901db1a1/labs/09/morpho_dataset.py#L35-L36). I don't know if this is done on purpose or not, but I am guessing that it's not because both have characters added [here](https://github.com/ufal/npfl114/blob/a339f9ecc5bc71a719e56a507db9e1c8901db1a1/labs/09/morpho_dataset.py#L54).

**Comment by foxik** [comment]
Thanks a lot for pointing it out (a community-work point is yours ;-)

It is actually an error, which was caused by me adding the types, copy-pasting the line, and not updating the value of EOF to 2. Last year, the MorphoDataset looked like this: https://github.com/ufal/npfl114/blob/69e0b21618afa1f53cf114f22f9bbfc9226fe11f/labs/08/morpho_dataset.py#L31

Luckily, it does not make the results worse, because:
- we use the BOW/EOW only in the lemmatizer
- BOW is used only on input and EOW only on output of the decoder, and we do not tie the embeddings, so even if BOW and EOW have errorneously the same ID, they get different embeddings anyway :-)

I will fix the error in the dataset, however, not immediately (given that changing it would change the results of `lemmatizer_*` assignments marginally -- the problem is that the EOW=2 embedding would be differently initialized, causing minor differences in the results). I therefore just added a comment in https://github.com/ufal/npfl114/commit/77016f13bf1ce8135a2fa05948b2dd7475ae13c2 and will fix after the end of the semester.
