### ISSUE TITLE
mnist package

### ISSUE THREAD

**Issue by jinymusim** [ufal/npfl114#85]
In pca_first.py there is a line

from mnist import MNIST

but this mnist package is nowhere.
Even after installing tf and gym, it gives errors.

**Comment by foxik** [comment]
Hi,

the `mnist.py` is a module present also in the repository, i.e., you need to download it too.

I have modified the task description to contain a link to it and added you a community work point ;-)

Cheers,\
Milan S.

**Comment by jinymusim** [comment]
mnist_layers_activations.py has the same problem
mnist.py is also missing (maybe add the link there as well?)

**Comment by foxik** [comment]
Yes, it is true that `mnist_layers_activations` is also using `mnist.py` -- but so will many other tasks (and they will depend on other modules than just `mnist.py` too). So I thought that adding it to `pca_first` will be enough (so that students realize that there can be other dependencies in the labs directory), and I did not want to clobber the description with a list of dependencies.

But I will think about it. Maybe use another "badge" (like the deadlines and the points) to list all the required files would make sense? Right now all the templates are referenced from the plain text, but having a systematic place where they would be listed would be better anyway? What do you think?
